<?php

return [
    [
        'key' => 'information',
        'name' => 'admin.layouts.information',
        'route' => 'admin.dashboard.index',
        'sort' => 1,
        'icon-class' => 'dashboard-icon',
    ],
    [
        'key' => 'information.dashboard',
        'name' => 'admin.layouts.dashboard',
        'route' => 'admin.dashboard.index',
        'sort' => 1,
        'icon-class' => 'dashboard-icon',
    ],
//    [
//        'key' => 'sales',
//        'name' => 'admin.layouts.sales',
//        'route' => 'admin.sales.orders.index',
//        'sort' => 2,
//        'icon-class' => 'sales-icon',
//    ],
//    [
//        'key' => 'sales.orders',
//        'name' => 'admin.layouts.orders',
//        'route' => 'admin.sales.orders.index',
//        'sort' => 1,
//        'icon-class' => '',
//    ],
//    [
//        'key' => 'sales.shipments',
//        'name' => 'admin.layouts.shipments',
//        'route' => 'admin.sales.shipments.index',
//        'sort' => 2,
//        'icon-class' => '',
//    ],
//    [
//        'key' => 'sales.invoices',
//        'name' => 'admin.layouts.invoices',
//        'route' => 'admin.sales.invoices.index',
//        'sort' => 3,
//        'icon-class' => '',
//    ],
    [
        'key' => 'catalog',
        'name' => 'admin.layouts.catalog',
        'route' => 'admin.catalog.products.index',
        'sort' => 3,
        'icon-class' => 'catalog-icon',
    ],
    [
        'key' => 'catalog.products',
        'name' => 'admin.layouts.products',
        'route' => 'admin.catalog.products.index',
        'sort' => 1,
        'icon-class' => '',
    ],
    [
        'key' => 'catalog.categories',
        'name' => 'admin.layouts.categories',
        'route' => 'admin.catalog.categories.index',
        'sort' => 2,
        'icon-class' => '',
    ],
//    [
//        'key' => 'catalog.attributes',
//        'name' => 'admin.layouts.attributes',
//        'route' => 'admin.catalog.attributes.index',
//        'sort' => 3,
//        'icon-class' => '',
//    ],
//    [
//        'key' => 'catalog.families',
//        'name' => 'admin.layouts.attribute-families',
//        'route' => 'admin.catalog.families.index',
//        'sort' => 4,
//        'icon-class' => '',
//    ],
    [
        'key' => 'customers',
        'name' => 'admin.layouts.customers',
        'route' => 'admin.customer.index',
        'sort' => 4,
        'icon-class' => 'customer-icon',
    ],
    [
        'key' => 'customers.customers',
        'name' => 'admin.layouts.customers',
        'route' => 'admin.customer.index',
        'sort' => 1,
        'icon-class' => '',
    ],
//    [
//        'key' => 'customers.groups',
//        'name' => 'admin.layouts.groups',
//        'route' => 'admin.groups.index',
//        'sort' => 2,
//        'icon-class' => '',
//    ],
//    [
//        'key' => 'customers.reviews',
//        'name' => 'admin.layouts.reviews',
//        'route' => 'admin.customer.review.index',
//        'sort' => 3,
//        'icon-class' => '',
//    ],
//    [
//        'key' => 'customers.subscribers',
//        'name' => 'admin.layouts.newsletter-subscriptions',
//        'route' => 'admin.customers.subscribers.index',
//        'sort' => 4,
//        'icon-class' => '',
//    ],
//    [
//        'key' => 'configuration',
//        'name' => 'admin.layouts.configure',
//        'route' => 'admin.configuration.index',
//        'sort' => 5,
//        'icon-class' => 'configuration-icon',
//    ],
//    [
//        'key' => 'settings',
//        'name' => 'admin.layouts.settings',
//        'route' => 'admin.locales.index',
//        'sort' => 6,
//        'icon-class' => 'settings-icon',
//    ],
//    [
//        'key' => 'settings.locales',
//        'name' => 'admin.layouts.locales',
//        'route' => 'admin.locales.index',
//        'sort' => 1,
//        'icon-class' => '',
//    ],
//    [
//        'key' => 'settings.currencies',
//        'name' => 'admin.layouts.currencies',
//        'route' => 'admin.currencies.index',
//        'sort' => 2,
//        'icon-class' => '',
//    ],
//    [
//        'key' => 'settings.exchange_rates',
//        'name' => 'admin.layouts.exchange-rates',
//        'route' => 'admin.exchange_rates.index',
//        'sort' => 3,
//        'icon-class' => '',
//    ],
//    [
//        'key' => 'settings.inventory_sources',
//        'name' => 'admin.layouts.inventory-sources',
//        'route' => 'admin.inventory_sources.index',
//        'sort' => 4,
//        'icon-class' => '',
//    ],
//    [
//        'key' => 'settings.channels',
//        'name' => 'admin.layouts.channels',
//        'route' => 'admin.channels.index',
//        'sort' => 5,
//        'icon-class' => '',
//    ],
//    [
//        'key' => 'settings.users',
//        'name' => 'admin.layouts.users',
//        'route' => 'admin.users.index',
//        'sort' => 6,
//        'icon-class' => '',
//    ],
//    [
//        'key' => 'settings.users.users',
//        'name' => 'admin.layouts.users',
//        'route' => 'admin.users.index',
//        'sort' => 1,
//        'icon-class' => '',
//    ],
//    [
//        'key' => 'settings.users.roles',
//        'name' => 'admin.layouts.roles',
//        'route' => 'admin.roles.index',
//        'sort' => 2,
//        'icon-class' => '',
//    ],
//    [
//        'key' => 'settings.sliders',
//        'name' => 'admin.layouts.sliders',
//        'route' => 'admin.sliders.index',
//        'sort' => 7,
//        'icon-class' => '',
//    ],
//    [
//        'key' => 'settings.taxes',
//        'name' => 'admin.layouts.taxes',
//        'route' => 'admin.tax-categories.index',
//        'sort' => 8,
//        'icon-class' => '',
//    ],
//    [
//        'key' => 'settings.taxes.tax-categories',
//        'name' => 'admin.layouts.tax-categories',
//        'route' => 'admin.tax-categories.index',
//        'sort' => 1,
//        'icon-class' => '',
//    ],
//    [
//        'key' => 'settings.taxes.tax-rates',
//        'name' => 'admin.layouts.tax-rates',
//        'route' => 'admin.tax-rates.index',
//        'sort' => 2,
//        'icon-class' => '',
//    ]
];